GET http://localhost:3000/users
###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "full_name": "Lama Lamarok",
    "email": "lama@email.com",
    "password": "secret123"
}
###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "chernia@email.com",
    "password": "secret123"
}
###

GET http://localhost:3000/bills/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjQ3NTE2NzY3LCJleHAiOjE2NDc1MjAzNjd9.fEZ0phpRnTy1WO4uA7orheDcXv2-lic1D0EG-Rrrd2Q
###

POST http://localhost:3000/bills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjQ3NTE2NzY3LCJleHAiOjE2NDc1MjAzNjd9.fEZ0phpRnTy1WO4uA7orheDcXv2-lic1D0EG-Rrrd2Q

{
      "group_id": 1,
      "amount": 120,
      "description": "For natural gas, electricity, water and central heating."
}
###

GET http://localhost:3000/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjQ3NTE2NzY3LCJleHAiOjE2NDc1MjAzNjd9.fEZ0phpRnTy1WO4uA7orheDcXv2-lic1D0EG-Rrrd2Q

###

POST http://localhost:3000/accounts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjQ3NTE2NzY3LCJleHAiOjE2NDc1MjAzNjd9.fEZ0phpRnTy1WO4uA7orheDcXv2-lic1D0EG-Rrrd2Q

{
      "group_id": 1
}

###

POST http://localhost:3000/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjQ3NTU1NjQyLCJleHAiOjE2NDc1NTkyNDJ9.DIBBbGbzjh22Oqx2jfySj3i_QneeJwqOCt-ukGOpHWw

{
      "name": "For McDonalds"
}
###
